---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "copyparty.fullname" . }}-config

  labels:
    {{- include "copyparty.labels" . | nindent 4 }}
    volume: config
spec: {{ toYaml .Values.persistence.volumeClaimSpec | nindent 2 }}